export const KEYWORD_MAX_LENGTH = 100;
export const PAGINATION_OPTIONS_DEFAULT_PAGE = 1;
export const PAGINATION_OPTIONS_DEFAULT_LIMIT = 50;
export const PAGINATION_OPTIONS_DEFAULT_MIN_LIMIT = 10;
export const PAGINATION_OPTIONS_DEFAULT_MAX_LIMIT = 100;

export const API_TABLE_DEFAULT_PAGE_SIZE = 1000;
