class EntityType:
    BLOCK = 'block'
    TRANSACTION = 'transaction'
    RECEIPT = 'receipt'
    LOG = 'log'
    TOKEN_TRANSFER = 'token_transfer'
    TRACE = 'trace'
    CONTRACT = 'contract'
    TOKEN = 'token'

    # NON_TOKEN_TRACE_SUPPORT = [BLOCK, TRANSACTION, LOG, TRACE, CONTRACT]
    ALL_TRACE_SUPPORT = [BLOCK, TRANSACTION, LOG, TOKEN_TRANSFER, TRACE, CONTRACT, TOKEN]
    ALL_NO_TRACE_SUPPORT = [BLOCK, TRANSACTION, LOG, TOKEN_TRANSFER]
