version: "3.7"
name: octan-pipeline-poc

networks:
  octan-pipeline-poc:
    driver: bridge
services:
  spark-iceberg:
    image: spark-iceberg
    container_name: spark-iceberg
    build: docker/spark-iceberg
    networks:
      octan-pipeline-poc:
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001

  exporter:
    container_name: exporter
    image: evm-etl
    build: indexer/
    depends_on:
      - spark-iceberg
    networks:
      - octan-pipeline-poc
    volumes:
      - ./warehouse:/ethereumetl/warehouse
    command: export_all -s 0 -e 5999 --provider-uri http://52.220.158.144:8545 -o /ethereumetl/warehouse