# docker-compose.yml
version: "3.8"

services:
  cmc_historical_crawl:
    build:
      context: .
      dockerfile: Dockerfile
    image: octanlabs/cmc-historical-crawl:latest
    env_file: ./.env
    volumes:
      - ./:/cmc-crawl
    command: npm start
