apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-lighter
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/spark-lighter
subjects:
  - kind: ServiceAccount
    name: lighter
    namespace: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit # careful with this
