apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
  labels:
    app: hive-metastore
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
        - image: trmaphi/hive-metastore:3.0.0-3.2.0-mysql
        - ports:
            - containerPort: 9083
        - env:
            - name: DATABASE_HOST
              value: admin
            - name: DATABASE_DB
              value: metastore_db
            - name: DATABASE_USER
              value: admin
            - name: DATABASE_PASSWORD
              value: admin
            - name: S3_PREFIX
              value: warehouse