apiVersion: batch/v1
kind: Job
metadata:
  name: 'bsc-indexing'
spec:
  completions: 100 # Int (Current block / 10000) 
  parallelism: 1 # Increase up to 3 then 5 when indexer is stable
  completionMode: Indexed
  backoffLimit: 10
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: 'indexer'
        image: 'trmaphi/evm-indexer:0.0.7'
        env:
          - name: PARTITION_BATCH_SIZE
            value: "10000"
          - name: FIRST_WORKER_PARTITION_INDEX
            value: "0"
          - name: CHAIN
            value: bsc
          - name: PROVIDER_URI
            value: "https://bsc-dataseed1.binance.org"
          - name: OUTPUT_DIR
            value: "s3://bsc-archive"
          - name: FSSPEC_S3_ENDPOINT_URL
            value: https://play.min.io:9000
          - name: FSSPEC_CACHE_REGIONS
            value: "true"
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_ACCESS_KEY_ID
            value: Q3AM3UQ867SPQQA43P2F
          - name: AWS_SECRET_ACCESS_KEY
            value: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
        args:
          - export_all_indexed_job
        volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir: {}