name: Publish DockerHub

on:
  push:
    tags:
       - 'spark-history-server-v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Version info
        id: version_info
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      -
        name: Semver
        id: sem_ver
        run: |
            SEM_VER=$(echo ${{ steps.version_info.outputs.SOURCE_TAG }} | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
            echo ::set-output name=SEM_VER::$SEM_VER
      -
        name: Build and push spark-history-server
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:docker/spark-history-server"
          push: true
          tags: octanlabs/spark-history-server:latest, octanlabs/spark-history-server:${{ steps.sem_ver.outputs.SEM_VER }}