name: Publish DockerHub

on:
  push:
    tags:
       - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Version info
        id: version_info
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      -
        name: Semver
        id: sem_ver
        run: |
          echo ::set-output name=SEM_VER::${SOURCE_TAG##*-}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:indexer"
          push: true
          if: ${{ startsWith(steps.version_info.outputs.SOURCE_TAG, 'ethereumetl-') }}
          tags: octanlabs/ethereumetl:latest, octanlabs/ethereumetl:${{ steps.sem_ver.outputs.SEM_VER }}
      -
        name: Build and push cmc crawl image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:cmc-crawl"
          file: historical.Dockerfile
          push: true
          if: ${{ startsWith(steps.version_info.outputs.SOURCE_TAG, 'cmc-historical-crawl-') }}
          tags: octanlabs/cmc-historical-crawl:latest, octanlabs/cmc-historical-crawl:${{ steps.sem_ver.outputs.SEM_VER }}
      -
        name: Build and push cmc crawl image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:cmc-crawl"
          file: historical.Dockerfile
          push: true
          if: ${{ startsWith(steps.version_info.outputs.SOURCE_TAG, 'top-cmc-crawl-') }}
          tags: octanlabs/top-cmc-crawl:latest, octanlabs/top-cmc-crawl:${{ steps.sem_ver.outputs.SEM_VER }}